### ISSUE TITLE
Links to manuals not searchable

### ISSUE THREAD

**Issue by genotrance** [schmidh/Nim-Docset-Files#1]
Nice work getting this setup and automated.

Only feedback is that all the manuals are not indexed in the search so I cannot just search for `manual`, `compiler`, `experimental`, `destructors`, etc. and get those specific pages.

**Comment by schmidh** [comment]
Hi Ganesh,

to make it more specific: what would you expect to find searching for `destructors`?

**Comment by genotrance** [comment]
Here are some of the links that aren't indexed but have to be manually navigated to. Not sure how many in total but some examples:

/Nim.docset/Contents/Resources/Documents/manual.html
/Nim.docset/Contents/Resources/Documents/lib.html
/Nim.docset/Contents/Resources/Documents/nimc.html
/Nim.docset/Contents/Resources/Documents/destructors.html
/Nim.docset/Contents/Resources/Documents/manual_experimental.html
/Nim.docset/Contents/Resources/Documents/docgen.html

**Comment by schmidh** [comment]
You are using Dash/Zeal as a full-text search engine which it is not. Entries have to be categorized. That's  why you would have needed another search engine to search your search results.
